spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: "*"
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api/v1/

application:
  frontend:
    url: ${FRONTEND_URL}
    activation-url: ${ACTIVATE_ACCOUNT_URL}
  security:
    jwt:
      secret-key: BC199D34B007BD069B98B8B3587C3B38D2A242EB42FA318678D1D3FF99F98FED
      access-token:
        expiration: 3600000
      refresh-token:
        expiration: 604800000